/*********************************************************************
 * Copyright (c) 2026 Contributors to the Eclipse Foundation.
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Smart City Jena
 **********************************************************************/

/*
 * Generated by scripts/i18n.mjs sync - the texts of this package, one file
 * per language in this folder. lib.i18next collects every 'Translations'
 * service, so these texts arrive with this bundle and leave with it.
 */
import { component } from '@eclipse-daanse/tsm'
import lang_de from './de.json'
import lang_en from './en.json'

export const NAMESPACE = 'tableKpi'

@component({
  service: ['Translations'],
  properties: { 'i18n.namespace': NAMESPACE },
})
export class TableKpiTranslations {
  readonly namespace = NAMESPACE
  readonly resources: Record<string, Record<string, unknown>> = {
    de: lang_de,
    en: lang_en,
  }
}
