name: 'Electron'
on:
  workflow_run:
    workflows:
      - 'CI'
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20.x
      - name: Install Lerna
        working-directory: .
        run: yarn global add lerna

      - name: Install
        working-directory: .
        run: yarn --skip-integrity-check --no-lockfile --network-timeout 100000
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build all Modules
        working-directory: .
        run: yarn run build
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Build
        working-directory: ./packages/app/electron
        run: yarn run copy_app_files

      - name: Publish Electron app
        working-directory: ./packages/app/electron
        run: yarn run publish@electron
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
