name: PR daanse Trigger

on:
  issue_comment:
    types: [ created ]

permissions:
  issues: write
  pull-requests: write

jobs:
  post-ad-message:
    if: |
      github.event.issue.pull_request != null &&
      contains(github.event.comment.body, '/daanse')
    runs-on: ubuntu-latest
    steps:
      - name: Post daanse message to PR
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            const prNumber = context.issue.number;
            const message = [
              "👋 Hey there! Thanks for triggering this action.",
              "",
              "🚀 I will daanse!"
            ].join("\n");

            await github.rest.issues.addLabels({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["daanse-requested"]
            });
            await github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
