name: 'Publish next'
on:
  workflow_run:
    workflows:
      - 'CI'
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    env:
      changes: true
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          # To fetch all history for all branches and tags.
          # Required for lerna to determine the version of the next package.
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_commit.id || github.sha }}

      - name: Restore Build Output from Cache
        uses: actions/cache/restore@3624ceb22c1c5a301c8db4169662070a689d9ea8 # v4.1.1
        with:
          path: dist
          key: build-cache-${{ github.sha }}
          restore-keys: |
            build-cache-

      - uses: actions/setup-node@v4
        with:
            node-version: '20.x'
            registry-url: 'https://registry.npmjs.org'
            # Defaults to the user or organization that owns the workflow file
            scope: '@octocat'
      #- name: Build
      #  run: yarn --skip-integrity-check --network-timeout 100000
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://github.com/microsoft/vscode-ripgrep/issues/9
      - name: Publish NPM
        run: yarn publish --no-git-tag-version --access public --preid next --prerelease
        env:
          NPM_CONFIG_PROVENANCE: 'true'
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

